### ISSUE TITLE
Update Behat to friends-of-behat/symfony-extension 2

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/php-ddd-example#85]
We finally have a stable release of the Behat support for Symfony 4 🎉

[Here we have all the information regarding the good news](https://kamilkokot.com/tame-behat-with-the-brand-new-symfony-extension/) 🙂

Some _cosa fina_ news 😬:

>The extension provides a dependency injection configuration which automatically finds your contexts and autowires them:
```yaml
# config/services_test.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
```

😱😱😱
